apiVersion: v1
kind: Pod 
metadata:
  name: front-end
  labels:
    front-end: app
spec:
  containers:
  - image: satyant1999/test:v1
    name: front-end
    ports:
    - name: front-end-port
      containerPort: 4200
